app/src/main/java/eu/kanade/tachiyomi/ui/library/AddToLibraryCategoriesDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourcePresenter.kt, app/src/main/res/values/strings.xml
makes it more clear in browse and manga details when adding a manga
=> Add a new manga category dialog

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryListHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/MangaHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceListHolder.kt, app/src/main/res/layout/manga_list_item.xml
=> condense list view

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceController.kt, app/src/main/res/layout/display_bottom_sheet.xml, app/src/main/res/values/strings.xml
=> add XS and XL options to grid view

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt
fix anilist jsonnull issue
reported here https://github.com/CarlosEsco/Neko/issues/190
added chucker to help with debugging stuff noops will not run chucker on release builds
upped retrofit version
=> fixed Anilist status can return null

README.md
added another ) after the taken from Neko
=> add a closing bracket line 35

app/src/main/res/layout/library_category_header_item.xml
=> move refresh to front of category name

app/src/main/res/values-pl/strings.xml
Updated polish translation for the new UI
=> Update of polish translation of strings.xml

app/src/main/res/values-ru/strings.xml
When translating, there were noticed flaws / bugs in the interface
<details>
</details>
Part managed to fix the translation adaptation
<details>
</details>
Please fix!
=> Russian localization

app/src/main/res/values-ru/strings.xml
Fix this https://github.com/Jays2Kings/tachiyomiJ2K/pull/298
=> String error correction-reword 

app/src/main/java/eu/kanade/tachiyomi/Migrations.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsPresenter.kt
should close #411 
i think the problem was a missing &&
```
val shouldDownload = !controller.fromCatalogue && mangaWasInitalized
(downloadNew && (categoriesToDownload.isEmpty() || getMangaCategoryIds().any { it in categoriesToDownload }))
```
either way i moved the logic to not even check the categories should download if it doesnt pass the first boolean checks. to stop unneeded processing
=> fix new chapter auto downloading when disabled

app/src/main/java/eu/kanade/tachiyomi/App.kt, app/src/main/java/eu/kanade/tachiyomi/data/image/coil/ByteArrayFetcher.kt, app/src/main/java/eu/kanade/tachiyomi/data/image/coil/CoilSetup.kt, app/src/main/java/eu/kanade/tachiyomi/data/image/coil/CoverViewTarget.kt, app/src/main/java/eu/kanade/tachiyomi/data/image/coil/LibraryMangaImageTarget.kt, app/src/main/java/eu/kanade/tachiyomi/data/image/coil/MangaFetcher.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryListHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/manga/process/MigrationProcessHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent_updates/RecentChapterHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recently_read/RecentlyReadHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recents/RecentMangaHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceListHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/global_search/GlobalSearchMangaHolder.kt
move coil package out of downloads since it doesnt quite make sense there
move the cover image target into coil
=> Move coil package

app/src/main/java/eu/kanade/tachiyomi/AppModule.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderChapterFilter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
move chapter filtering to its own class and injekt it.
Clean up the logic around the filter to prevent unneeded filtering and to make it more understandable
=> Clean up the reader filter logic

app/src/main/res/values-pt-rBR/strings.xml
Some modifications and other lines of translation added.
=> Update for Portuguese translation

app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, settings.gradle.kts
clean up of plugin to use classpath so it can use the kotlin class instead of having to intercept in the settings.gradle
=> move some gradle plugin stuff around

app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListInterceptor.kt
=> add 400 response login refresh for mal

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsPresenter.kt
pretty straight forward, hashsets are fast
reduce the looping
should fix #535
=> fix download cache performance issue

app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
Fix https://github.com/inorichi/tachiyomi-extensions/issues/3516
Mentioned fix by arkon from https://github.com/inorichi/tachiyomi/commit/a1061040271fe0a807b5bfdb0ecb926e15364847
=> enable WebView DOM storage

app/src/main/res/values-de/strings.xml
=> German translation updates

app/src/main/java/eu/kanade/tachiyomi/source/SourceManager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsController.kt, app/src/main/res/menu/chapter_single.xml, app/src/main/res/menu/library_selection.xml, app/src/main/res/values/strings.xml
add ability from Neko to 
mark previous as unread when long pressing a chapter
in library
download unread, mark as read, mark as unread
=> added library status options and chapter 

app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/Shikimori.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/ShikimoriApi.kt
Add remove from tracking https://shikimori.one tracking service
=> J2k. Remove from shikimori

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
Closes #703 
Co-Authored-By: jobobby04 jobobby04@gmail.com
=> Seearch by manga description in Library

app/src/main/java/eu/kanade/tachiyomi/util/system/ThemeUtil.kt, app/src/main/res/color/primary_button_text_color_selector.xml, app/src/main/res/layout/source_global_search_controller_card_item.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Library Badge line 44 is where you need to use the ?attr/colorOnAccent  I kept getting a resource error trying to compile.
=> Added hot pink and lime

app/src/main/res/values-es/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml
Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: Lusuho <jevpsychox@gmail.com>
Co-authored-by: Lyaiya <hipsnafoha@outlook.com>
Co-authored-by: Milo Ivir <mail@milotype.de>
Co-authored-by: waitingmoon <takeda.s1027@gmail.com>
Co-authored-by: Роман <Rozhenkov69@gmail.com>
Translate-URL: https://hosted.weblate.org/projects/tachiyomi/tachiyomi-j2k/es/
Translate-URL: https://hosted.weblate.org/projects/tachiyomi/tachiyomi-j2k/hr/
Translate-URL: https://hosted.weblate.org/projects/tachiyomi/tachiyomi-j2k/ja/
Translate-URL: https://hosted.weblate.org/projects/tachiyomi/tachiyomi-j2k/ru/
Translate-URL: https://hosted.weblate.org/projects/tachiyomi/tachiyomi-j2k/zh_Hans/
Translation: Tachiyomi/Tachiyomi J2K
=> Weblate translations

app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/BrowseSourceListHolder.kt, app/src/main/res/layout/in_library_badge.xml, app/src/main/res/layout/manga_list_item.xml
Text gets off with current way 
new
old
=> use a badge instead of in library text for list view 

app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sc/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml
**Merge just before next release** or when there's a significant amount of translations waiting
**Don't** merge if push healthcheck is not up: [![Healthcheck](https://healthchecks.io/badge/547fbf65-f63a-4513-a455-071a44/giw6-Y5g.svg)](https://healthchecks.io/checks/9d0ad96f-ea6f-470d-911a-17ac190c5fec/details/)
Continues from #885 
More information: https://tachiyomi.org/help/contribution/#translation
[![Translation status](https://hosted.weblate.org/widgets/tachiyomi/-/tachiyomi-j2k/multi-auto.svg)](https://hosted.weblate.org/engage/tachiyomi/)
=> Translations (Continuous) 

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaHeaderHolder.kt, app/src/main/res/layout-sw600dp-land/manga_header_item.xml, app/src/main/res/layout-sw600dp-port/manga_header_item.xml, app/src/main/res/layout/genre_chip.xml, app/src/main/res/layout/manga_header_item.xml, app/src/main/res/values/styles.xml
Already shared screens through discord, just need to modify the edit manga screen if you want to remove the library
=> switch genre tags to material chips

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/model/InsertPage.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/model/ReaderPage.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/settings/PageLayout.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt, app/src/main/res/drawable/ic_book_open_split_24dp.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Splitting double pages

app/src/main/java/eu/kanade/tachiyomi/data/database/DbOpenCallback.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/MangaTypeMapping.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/MangaImpl.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaFilteredScanlatorsPutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/tables/MangaTable.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersSortBottomSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterFilter.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSort.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterUtil.kt, app/src/main/res/layout/chapter_sort_bottom_sheet.xml, app/src/main/res/values/strings.xml
attempt at adding scanlation filter with the help of carlos and syer's code.
=> add scanlation filter

app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
adds debug info to crashlog like tachiyomi
=> add debug info to crashlog

app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt
fixes search not working over 64 chars and novels showing up in search
=> cherry pick some MAL fixes

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/values/strings.xml
Adding 5% side padding, as 10% side padding making webtoons thin to read.
=> Side padding: Added missing percentage

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsController.kt, app/src/main/res/menu/manga_details.xml
To avoid using the file explorer or removing one by one
=> Add custom range for remove downloads in manga details

app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
=> Fix concurrent download

app/src/main/java/eu/kanade/tachiyomi/data/backup/AbstractBackupManager.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupConst.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt, app/src/main/res/values/strings.xml
=> Add option to backup read manga not in library

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt
Downloads are stucked sometimes. I think it's because it was missing the `wakelock.acquire()` call
=> Fix stucked downloads wakelock

app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/details/StatsDetailsController.kt
When you click on the `clear filters` icon, everything is reset even the stat and sort selection but the icon doesn't appear when you change the selection of one of these two. So it makes more sense to remove them from the `clear filters`. Another option would be to show the `clear filters` when they are changed, let me know if you prefer this option
And just a bit of cleanup
=> Stats: Exclude stat and sort from clear filters

app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt
Makes all items from readcomiconline be tagged as comic instead of manga
=> Fixes readcomiconline tagging

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt, app/src/main/java/eu/kanade/tachiyomi/util/view/ControllerExtensions.kt
I didn't get time to mess with it further, so I'm just going to pr what I have. It seems to work for the most part but I couldn't really test. The issues I saw is that it still sets it up even if you deny permissions, but considering the discussion on discord, the other way we were going to do is just turning it on and letting it fail silently anyways...
=> add auto backup on permissions granted

app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
I noticed an issue with current splitting method where in webtoons there can be a flickering black line between pages when reading long strip pages. I updated to upstream method which doesn't have that issue.
=> Fixed long strip splitting method causing flickering black line

app/src/main/java/eu/kanade/tachiyomi/extension/api/ExtensionApi.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/details/ExtensionDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/repos/RepoController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/repos/RepoHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/source/browse/repos/RepoPresenter.kt
- Add error when repo already exists
- Open github repo when click on logo if possible
- Fix onClickListener asking to delete instead of opening browser
=> Fixes extension repos

app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiModels.kt
Try to  fix. 
#1560 #1818 #820
=> fix: Crash when switching to next chapter
