Jays2Kings/tachiyomiJ2K

- app/build.gradle.kts
- app/src/main/java/eu/kanade/tachiyomi/App.kt
Fix https://github.com/inorichi/tachiyomi-extensions/issues/3233.
Cheery-picked from arkon@31015504f4d0df3d0a4b185fb754f1224dfe1c0c, and changed to Kotlin version.
> TLS 1.3 support for Android < 10

- app/build.gradle.kts
I pulled your fork's changes into the "main fork": https://github.com/tachiyomiorg/subsampling-scale-image-view/commits/tachiyomi
This version also includes some stuff like bumped up minSdk, some updated image libs, etc.
> Use Tachiyomiorg version of subsampling-scale-image-view

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt
I added the default category in the library preference "Categories to include in global update".
In my case I wanted to be able to create a category that won't update automatically. But it was not possible to only choose the default category for the global update.
> Adding Default categorie in global update pref

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
The option to save pages to separate subfolders based on manga title didn't sanitize the manga title in the subfolders' names, which made it impossible to save pages from manga with reserved characters in their titles with the option enabled. This commit aims to fix that by using DiskUtil.buildValidFilename to sanitize it.
Note: The commit in this PR is cherry-picked from the upstream Tachiyomi repository. I'm fairly new to Git and this is the cleanest way I could find to integrate my changes into this fork as well.
> Sanitize manga title in page download subfolder name

- app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt
fixes issue that @CarlosEsco mentioned in #1006 
chapter 5 and 6 is new chapters
chapter 5 is hidden by filter and chapter 6 is not.
video of testing
https://user-images.githubusercontent.com/57241064/134711409-e79a2e77-e0d7-41dd-8348-175d3dfb586d.mp4
possible issues that may need addressed:
I tested if you download a chapter and then hide it with the filter and the source deletes that chapter, the chapter will become orphaned. I previously had the 2nd pair, `toDelete - readded` filtered as well, and thought not filtering it would alleviate issue but it did not and have left it alone.
> fix downloading filtered out chapters

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/DownloadPageLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadController.kt
- app/src/main/res/values/strings.xml
Since I screwed up the last PR, I'm opening a new one...
Things tested:
-  Download and convert folder to cbz
-  Able to read cbz both online and offline
-  delete cbz when button is used and also in the top button
-  correctly show that download is deleted afterwards
- cleanup downloads correctly deletes file if orphaned and doesn't delete it if not orphaned
- download cache recognizes it with force refresh setting or restarting of app
I also agree with Carlos and removed the cbz compression level but we can easily add it back in if you want it.
~~Things that I noticed when playing around is that the cleanup downloads deletes all cbz downloads and I'm pretty sure its because I added [this](https://github.com/Seishirou101/tachiyomiJ2K/blob/9511786f8b545893215ca49f0d363d19271ebb11/app/src/m …
> compress to cbz after downloading

- app/src/main/java/eu/kanade/tachiyomi/AppInfo.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/network/interceptor/RateLimitInterceptor.kt
- app/src/main/java/eu/kanade/tachiyomi/network/interceptor/SpecificHostRateLimitInterceptor.kt
- app/src/main/java/eu/kanade/tachiyomi/source/UnmeteredSource.kt
- app/src/main/java/eu/kanade/tachiyomi/source/model/SManga.kt
Relevant extensions change: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11298
All lib changes: https://github.com/tachiyomiorg/extensions-lib/compare/1.2...1.3.0
This is the bare minimum to ensure J2K can load 1.3.x extensions. Of note, it doesn't do anything with the added `UnmeteredSource` interface nor show proper strings for the new manga statuses.
> Add required changes for extensions-lib 1.3

- app/src/main/res/layout/reader_activity.xml
This fixes #1200, #1203 and #927 by preventing the reader view from being focused when using a physical input device by adding the `android:descendantFocusability="blocksDescendants"` property to the viewer container, to match the main tachiyomi repo which doesn't have this issue.
> Remove color tint when using a physical input device to navigate

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
Fixed this a while ago for Sy and while I intended to PR to j2k, I kinda forgot xd
Refer issue from sy repo - https://github.com/jobobby04/TachiyomiSY/issues/542
Title: "Saving combined image in Dual page reader doesnt follow enabling `Save pages into separate folder` setting" 
Also kinda relevant: ghostbear subsequently updated the save/share logic to final remove the deprecated environment calls used there
Final changed `SaveImage` response: https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt#L586
Relevant PRs: https://github.com/tachiyomiorg/tachiyomi/pull/6787, https://github.com/tachiyomiorg/tachiyomi/pull/6800, https://github.com/tachiyomiorg/tachiyomi/pull/6827
> When saving dual-page, check folderPerManga pref

- app/src/main/java/eu/kanade/tachiyomi/data/backup/full/FullBackupManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Chapter.kt
Fixed: [[Bug] Restore backup - chapter read status #1256](https://github.com/Jays2Kings/tachiyomiJ2K/issues/1256)
Upstream has a different version of `copyFrom` that doesn't overwrite. So I tried to mimic the behavior without impacting anything else by adding an optional flag.
I have tested this with multiple test cases and it worked totally normal as expected.
> Fixed Restore Chapter Method

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt
Kinda useful if you only want to change a part of a field, especially if the original text is quite long (like those crazy ass long manga titles)
> Edit series's info: Append original text on long click if text is empty

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt
- app/src/main/res/layout/unread_download_badge.xml
Some minor fixes:
- In the `EditMangaDialog`, the `onItemSelectedListener` should be set before the `setSelection` otherwise the `originalSelection` is reset to blank and is not visible when we first open the series type (if the original was not already selected)
- For the library badges, I use a small font and the language flag's height was a bit bigger than the unread/download badges'. With these changes it should always have the same height
> Improves library badges when small font

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/util/storage/DiskUtil.kt
After downloading a manga cover, the cover was not visible in the gallery
I also modified `scanMedia()` since `Intent.ACTION_MEDIA_SCANNER_SCAN_FILE` is deprecated, I can revert it if you want
> Fix manga cover download

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
Closes #1293 
It should fix this crash. Not sure why `manga` is null though
Only either the modification of `getSource()` or putting the manga initialization earlier is necessary but well I did both, better be safe than sorry
> Fix manga not initialized in getSource

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaDetailsController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaHeaderHolder.kt
Hold on Favorite manga button to edit categories instead of clicking and then showing a popup.
Will reduce 2 clicks for removing manga from library and when editing categories
Closes https://github.com/Jays2Kings/tachiyomiJ2K/issues/1133
> Hold to edit manga categories instead of popup

- app/src/main/java/eu/kanade/tachiyomi/ui/migration/SourceHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/source/SourceHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/source/SourcePresenter.kt
I removed the `(lang)` after the source name for migration (in browse) page since you added the language below the source + fixed the number of items not visible when multi-language
I also added the `(lang)` for last used extension (same as pinned extensions)
> Fix language info extensions

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/database/ClearDatabaseController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/database/ClearDatabasePresenter.kt
- app/src/main/res/values/strings.xml
Taken from Sy
Useful for the read duration stats. Otherwise you will lose the stats of read manga deleted from library
Closes #688
> Add option to keep read manga in Clear Database

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/MiniSearchView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
- app/src/main/res/drawable/ic_show_all_categories_24dp.xml
- app/src/main/res/drawable/ic_unfold_less_horizontal_24dp.xml
- app/src/main/res/drawable/ic_unfold_more_horizontal_24dp.xml
This PR reverts the behavior introduced by #1312, and adds a toggle to show all categories during library search.
Supercedes #1375, which itself superceded #1340
The toggle is only visible when:
* A search is active
* A library is grouped by categories
* `Show all categories` is disabled
Tooltip on Long Press:
> Add toggle to searchbar  to force show all categories

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/HistoryQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/StatsController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/StatsPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/details/StatsDetailsPresenter.kt
- app/src/main/res/layout/list_chart_legend.xml
- app/src/main/res/layout/stats_controller.xml
- app/src/main/res/values/strings.xml
Just saw that the total read duration doesn't include all history, just the manga in library, so I changed that
And some visual changes:
- tweaked a bit the general stats in case there is a language with long words and to avoid setting the number of lines
- reorganized the stats to have more homogeneous description lines (not sure which is better between vertical centered or top, let me know if you have a preference)
- added tooltips for read duration and mean score
- converted the link to stats details to a button
- fixed the status distribution wrapping when the text + value are too long (wrap the description text instead of value now)
Also tweaked the details stats order to put the read duration higher
> Change read duration total to include all history

- app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/details/StatsDetailsController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/more/stats/details/StatsDetailsPresenter.kt
- app/src/main/res/layout-land/stats_details_controller.xml
Fix weird behavior when changing the stats period too fast which increased the days range + disappearance of the date picker/arrows when `no_chart_data` was displayed in landscape
> Fix stats range changed when using arrows

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadController.kt
- app/src/main/res/values/strings.xml
Adds a category filter for the `Remove after read` setting so that downloaded chapters are only deleted after being read in the configured categories. Resolves #1593 
It does not change how `Remove when marked as read` works, so that still deletes chapters in all categories
| Remove after read disabled | Enabled|
|--------|--------|
| ![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/31808958/ce299e71-75ba-4caf-b97e-42dc40a14131) | ![image](https://github.com/Jays2Kings/tachiyomiJ2K/assets/31808958/2e29f7ac-ae91-412b-be7e-5dece2b2bd54) |
> Category filter for remove after read

- app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
This adds extension info that is obsolete or out of date to the crashlog. It looks like
> add extension info to crashlog
